export HISTCONTROL=ignoredups:erasedups
HISTFILESIZE=1000000000 HISTSIZE=1000000
export EDITOR=vim

alias v='ls -lah'
alias u='cd ..'
alias u2='cd ../..'


if [ -f ~/.bash_env ]; then
	. ~/.bash_env
fi

alias www='cd /var/www'
cd /var/www

export LC_ALL=en_US.utf-8
export LANG="$LC_ALL"

bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'
